name: fragdockrl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26
  - pandas=2.3.1
  - rdkit=2023.09.6  
  - smina=2020.12.10
  - pytorch=2.7.1
  - pip
  - pip:
      - git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3.git
